#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        create_san_svm.yml 
# Author:       Ronald Feist
# Date:         2020-06-09
# Description:  Create a primary SVM for SAN
#               with Ansible modules
#
# Modules:      na_ontap_svm
#
# URLs:         http://docs.netapp.com/ontap-9/index.jsp
#               https://galaxy.ansible.com/netapp/ontap
#
# Built-in help:
# ansible-doc netapp.ontap.na_ontap_svm
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
# root_volume_aggregate currently not supported with REST
#      use_rest:       Always
  vars_files:
    - global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create primary SVM
    na_ontap_svm:
      state:                 present
      name:                  "s2_{{ PRI_SVM }}"
      root_volume_aggregate: "{{ PRI_AGGR_02 }}"
      comment:               Created with Ansible
      <<: *input
  - name: Add iSCSI service
    na_ontap_svm:
      state:                 present
      name:                  "s2_{{ PRI_SVM }}"
      services:
         iscsi:
           enabled: true
      <<: *input
  - name: Create first iSCSI LIF 
    na_ontap_interface:
      state:                 present
      interface_name:        "s2_{{ PRI_SVM }}_iscsi_01"
      vserver:               "s2_{{ PRI_SVM }}"
      address:               "{{ PRI_ISCSI_IP }}"
      netmask:               "{{ PRI_SVM_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE1 }}"
      home_port:             "{{ PRI_DATA_PORT }}"
      protocols:             iscsi
      firewall_policy:       data
      role:                  data
      <<: *input
  - name: Create second iSCSI LIF 
    na_ontap_interface:
      state:                 present
      interface_name:        "s2_{{ PRI_SVM }}_iscsi_02"
      vserver:               "s2_{{ PRI_SVM }}"
      address:               "{{ SEC_ISCSI_IP }}"
      netmask:               "{{ PRI_SVM_NETMASK }}"
      home_node:             "{{ PRI_CLU_NODE2 }}"
      home_port:             "{{ PRI_DATA_PORT }}"
      protocols:             iscsi
      firewall_policy:       data
      role:                  data
      <<: *input
  - name: Create iGroup
    na_ontap_igroup:
      state:                present
      name:                 "s2_igroup"
      vserver:              "s2_{{ PRI_SVM }}"
      initiator_group_type: iscsi
      initiator_names:      "iqn.1991-05.com.microsoft:jumphost.demo.netapp.com"
      ostype:               "windows"
      <<: *input
  - name: Create volume
    na_ontap_volume:
      state: present
      name: "s2_san_vol"
      vserver: "s2_{{ PRI_SVM }}"
      aggregate_name: "{{ PRI_AGGR_02 }}"
      size: "10"
      size_unit: "gb"
      space_guarantee: "none"
      <<: *input
  - name: Lun Create
    na_ontap_lun:
      state: present
      name: s2_lun1
      vserver: "s2_{{ PRI_SVM }}"
      flexvol_name: "s2_san_vol"
      size: "{{ LUN_SIZE }}"
      size_unit: gb
      ostype: windows
      space_reserve: false
      <<: *input
  - name: Create LUN mapping
    na_ontap_lun_map:
      state: present
      initiator_group_name: s2_igroup
      path: "/vol/s2_san_vol/s2_lun1"
      vserver: "s2_{{ PRI_SVM }}"
      <<: *input
